"""empty message

Revision ID: 81e7065dc2bb
Revises: 
Create Date: 2019-01-16 15:26:34.629616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e7065dc2bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('bill', sa.Float(), nullable=False),
    sa.Column('is_adm', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=60), nullable=False),
    sa.Column('number', sa.String(length=6), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Account')
    # ### end Alembic commands ###
